name: Sync WordPress & Deploy Hugo Site

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # runs every hour to sync WordPress posts
  workflow_dispatch:      # allows manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.151.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm install

      - name: Sync WordPress Posts
        env:
          WP_AUTH_USER: ${{ secrets.WP_AUTH_USER || vars.WP_AUTH_USER }}
          WP_AUTH_PASS: ${{ secrets.WP_AUTH_PASS || vars.WP_AUTH_PASS }}
        run: npm run sync

      - name: Commit new posts (if any)
        run: |
          git config user.name "Vinay Thoke"
          git config user.email "reachme@vinaythoke.com"
          git add content/post/
          if git diff --staged --quiet; then
            echo "No new posts to commit"
          else
            git commit -m "Auto-sync new posts from WordPress [skip ci]"
            git push
          fi

      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
          tar -xvzf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
          sudo mv hugo /usr/local/bin/hugo

      - name: Build Hugo site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: sync-and-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4