name: Sync WordPress Posts

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run sync script
        run: node scripts/sync-wp.mjs

      - name: Commit and push changes
        run: |
          git config user.name "Vinay Thoke"
          git config user.email "reachme@vinaythoke.com"
          git add content/post/
          git commit -m "Auto-sync new posts from WordPress" || echo "No changes to commit"
          git push
